# NOTE: This is a `cbindgen` config that's specific to the apple platforms, as
# only those platformw will have the TargetConditionals.h system header
# necessary to reliably detect between macOS and iPhone targets.
#
# See:
#   find /Applications/Xcode.app/Contents/Developer/Platforms -name 'TargetConditionals\.h'

language = "C"
sys_includes = ["TargetConditionals.h"]

after_includes = """
#if TARGET_OS_OSX
    #define OBSCURA_DEFINE_TARGET_OS_MACOS
#endif
"""

[defines]
"target_os = macos" = "OBSCURA_DEFINE_TARGET_OS_MACOS"
