accepted = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "OpenSSL",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "WTFPL",
    "Zlib",
    "Unlicense",
    "Apache-2.0 WITH LLVM-exception",
]

# DO NOT attempt to lookup licensing information from https://clearlydefined.io
no-clearly-defined = true

[obscuravpn-api]
# Our current version of cargo-about doesn't support "GPL-3.0-only"
accepted = ["GPL-3.0 WITH GPL-3.0-linking-source-exception"]

[obscuravpn-api.clarify]
license = "GPL-3.0 WITH GPL-3.0-linking-source-exception"

[[obscuravpn-api.clarify.files]]
checksum = "5e8dcaf12ba2d09383bc010383ecdda810423295c1c2820248daaa1c7c4ce01d"
path = "LICENSE"

[obscuravpn-client]
# Our current version of cargo-about doesn't support "GPL-3.0-only"
accepted = ["GPL-3.0 WITH GPL-3.0-linking-source-exception"]

[obscuravpn-client.clarify]
license = "GPL-3.0 WITH GPL-3.0-linking-source-exception"

[[obscuravpn-client.clarify.files]]
checksum = "5e8dcaf12ba2d09383bc010383ecdda810423295c1c2820248daaa1c7c4ce01d"
path = "../LICENSE"
